INSERT INTO AUTOR (nombre, apellido) values('Jorge Luis','Borges');
INSERT INTO AUTOR (nombre, apellido) values('Gabriel','Garcia Marquez');
INSERT INTO AUTOR (nombre, apellido) values('Franz','Kafka');
INSERT INTO AUTOR (nombre, apellido) values('Julio','Cortazar');

INSERT INTO GENERO (nombre) values('Cuentos');
INSERT INTO GENERO (nombre) values('Realismo magico');
INSERT INTO GENERO (nombre) values('Novela');
INSERT INTO GENERO (nombre) values('Accion');

INSERT INTO EDITORIAL (nombre) values('Losada');
INSERT INTO EDITORIAL (nombre) values('Sudamericana');
INSERT INTO EDITORIAL (nombre) values('Pantheon Books');
INSERT INTO EDITORIAL (nombre) values('Verlag Die Schmiede');	

INSERT INTO LIBRO (nombre,codigoeditorial,codigogenero,codigoautor) values('El Aleph',1,1,1);
INSERT INTO LIBRO (nombre,codigoeditorial,codigogenero,codigoautor) values('El proceso',4,3,3);
INSERT INTO LIBRO (nombre,codigoeditorial,codigogenero,codigoautor) values('Rayuela',3,3,4);
INSERT INTO LIBRO (nombre,codigoeditorial,codigogenero,codigoautor) values('Cien años de soledad',2,2,2);

INSERT INTO SOCIO (nombre,apellido,dni,telefono) values('Santiago', 'Bursese', '41588352','1149460415');
INSERT INTO SOCIO (nombre,apellido,dni,telefono) values('Carolina', 'Bursese', '44583763','1198454372');



 

